# stage 1
FROM node:18-alpine As builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build:prod
# RUN npm run watch

#stage 2
FROM nginx:alpine
COPY --from=builder /app/dist/parastaseis/ /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf