FROM node:18-alpine AS deps

WORKDIR /app
COPY package.json package-lock.json ./
# RUN npm install --ignore-scripts --legacy-peer-deps
RUN npm install 

FROM node:18-alpine
WORKDIR /app
COPY --from=deps app/node_modules node_modules
COPY . .
RUN npm i -g @nestjs/cli

# EXPOSE 3000

# CMD ["npm", "start"]
ENTRYPOINT ["npm", "run", "start:dev"]