[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$/IF7copW$MH2tm5q.jZS55jXgdsUGC1"
  ]

[http.routers.api]
  rule = "Host(`monitor.tsilingeridis.eu`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"