version: "3.9"
services:
  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./traefik.toml:/traefik.toml"
      - "./traefik_dynamic.toml:/traefik_dynamic.toml"
    networks:
      - proxy

networks:
  proxy:
    driver: overlay
